### PR TITLE
add MTU to networks

### PR DESCRIPTION
**Pull request by pilch-cit**
ocsreports is now able to show MTU of network interfaces

### CODE REVIEW

**Comment by gillesdubois** [comment]
Hi,

PR seem OK but you need to provide an additional thing if you want it to be integrated.

People who already have a fully installed database won't have the sql fields update (you need to fill the file in files/update/7010.sql with a query to add the MTU fields in the network table)

Regards,
Gilles Dubois.

**Comment by pilch-cit** [comment]
Hi,

thank you for merging despite the unmodified 7010,sql.

Best regards,
Alexander Pilch

**Comment by gillesdubois** [comment]
No problems i made the modification right after merging :)

MTU Inventory have been added to windows agent too : 
- https://github.com/OCSInventory-NG/WindowsAgent/commit/d05e538a9e4fe922c63bfaa186f2a580718c884b

Thanks for your contribution 👍 

Regards,
Gilles Dubois.

**Comment by pilch-cit** [comment]
That's great news about the windows agent.

You're welcome. :)

Best regards,
Alexander Pilch

**Pull request merged**
