### PR TITLE
Fix bug display success stat deployment

### PR DESCRIPTION
**Pull request by charleneauger**
### Status
**READY** (remove the irrevelant words)

### Description
Fix bug display success stat deployment

### Documentation
In the case, your pull request need the documentation to be modified, please say it here.
You can also directly create a pull request for the documentation here : https://github.com/OCSInventory-NG/Wiki

Note : Merge process will be faster if the documentation is already written

### CODE REVIEW

**Comment by fpotier** [comment]
image

Hi, thanks for this patch, it solved the JS error but it now says : "THE DATA DOESN'T EXIST. THE STATES HOURS CAN NOT BE FOUND IN DATABASE FOR THIS PACKAGE" when I try to see success or error stats.
So it seems like this [issue](https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1034) could be reopened.

**Comment by charleneauger** [comment]
Hi @fpotier ,

Can you execute the last query debug in mysql and return me the result please ?

Regards,
Charlene

**Comment by fpotier** [comment]
Hi @charleneauger ,

Thanks for your quick answer and your work to patch the JS error.

Here is the output of the query in mysql : 

```
MariaDB [(none)]> use ocsweb;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed

MariaDB [ocsweb]> SELECT d.hardware_id AS id,d.comments AS date_valid FROM devices d,download_enable d_e,download_available d_a WHERE d.name='DOWNLOAD' AND tvalue='SUCCESS' AND comments IS NOT NULL AND d_e.id=d.ivalue AND d_a.fileid=d_e.fileid AND d_e.fileid='1625239562';
+--------+--------------------------+
| id     | date_valid               |
+--------+--------------------------+
| 198799 | Fri Jul  9 15:50:15 2021 |
+--------+--------------------------+
1 row in set (0.001 sec)
```

Regards,
Frédéric

**Comment by charleneauger** [comment]
@fpotier,

The problem comes from the fact that you only have one result.

To give you some information about the graphic generated on this page, it consist of displaying the deployment success over time in percent. Thus, you will need more than one entry to get a working statistic :-) 

Best regards,
Charlene

**Comment by fpotier** [comment]
Oh my bad, I guess it makes sense now.
Thanks

**Pull request merged**
