### PR TITLE
Drop linfo from bundled libraries

### PR DESCRIPTION
**Pull request by remicollet**
Problems:
* license incompatibility (linfo is not a library, but an application, under GPLv3)
* security issue ocsreposrts//libraries/linfo/index.php is exposed to whole world without any protecttion, giving nice information tohackers

### CODE REVIEW

**Comment by remicollet** [comment]
Notice: in 1st commit, I also replace "Mysql version" with "Database server", and improves the report for MySQL / MariaDB.

**Comment by gillesdubois** [comment]
Hello, 

On that commit : https://github.com/remicollet/OCSInventory-ocsreports/commit/2147b89522a0d75d73d2ca1bc1d416286776d500 on line 32.

I think it would be better to add "/etc/suse-release" for a better compatibility with open suse 13 and earlier

Thx for contributing to OCSInventory-ng
Regards, Gilles Dubois

**Comment by remicollet** [comment]
@gillesdubois yes, as stated in the comment "TODO other distro"

I prefer to not add this without being able to check, especially as internet refers to /etc/SuSE-release not to /etc/suse-release ;)

Need someone to check on a real Suse distro.

**Comment by remicollet** [comment]
Well, added... internet seems to always refers to this name

**Comment by gillesdubois** [comment]
Yes, all sources on the internet are mentioning :  "/etc/SuSE-release"
I'm OK with your pull request everything is working, merged.
I've already tested this on OpenSUSE, it's working well but i think i will make an in depth test later :-)

Thanks you for contributing to OCSInventory-ng
Regards, Gilles Dubois

**Pull request merged**
