### PR TITLE
Update Language de_DE

### PR DESCRIPTION
**Pull request by LMS235**
Update Language de_DE

### Status
**READY** (remove the irrevelant words)

### Description
Update Language de_DE

### Documentation
Update Language de_DE

### CODE REVIEW

**Comment by gillesdubois** [comment]
Hi @LMS235 

Thanks for your contribution.

Your PR seems to be conflicting with our current master.
Can you update your PR please ?

Thanks.

Regards,
Gilles.

**Comment by LMS235** [comment]
done

**Comment by gillesdubois** [comment]
Thanks @LMS235 

I guess we'll trust you on this translation, my German is pretty bad :) 

Regards,
Gilles.

**Comment by LMS235** [comment]
the old one is also from me ;) https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/744

**Comment by gillesdubois** [comment]
Yes I saw that afterward, thanks for keeping our translation up to date :) 

Regards,
Gilles.

**Pull request merged**
