### PR TITLE
Adding Custom Interval Config to Last Contact Dashboard

### PR DESCRIPTION
**Pull request by wiltonsr**
### Status
**READY**

### Description
Make the dashboard Last Contact graph based on `INTERFACE_LAST_CONTACT` config.

### Documentation
Need the documentation to be updated

### CODE REVIEW

**Comment by charleneauger** [comment]
Hi @wiltonsr ,

We are going to release a new version soon so we won't implement this feature right now.
As soon as a new release is published, we will review it / merge it.

Thanks for your contribution.
Regards,
Charlene

**Comment by wiltonsr** [comment]
Hi, @charleneauger 

Thanks for the reply.

I updated my branch with master and fix the `7057.sql` file conflict.

**Review by charleneauger — CHANGES_REQUESTED** [review]

**Comment by charleneauger** [comment]
Hey @wiltonsr 

Thx for your contribution.

Could you also push the var.php file and set the GUI_VER to 7060 ?

Regards,
Charlene

**Comment by wiltonsr** [comment]
Hi @charleneauger 

All reviews changes done.

**Comment by charleneauger** [comment]
Hi @wiltonsr ,

Thanks, I merge ;)

Regards,
Charlene

**Pull request merged**
