### PR TITLE
Adjust Lines, Adjust German

### PR DESCRIPTION
**Pull request by LMS235**
### Status
**READY**

### Description
- Adjusted that line number and entry number are the same (simplifies the translation)
- Adjusted the German translation

### Documentation
n/a

### CODE REVIEW

**Comment by LMS235** [comment]
Is there something wrong with the request? Generally you should try to keep the line numbers and entry numbers the same, this makes it much easier to translate.

I have only done this for DE and EN (the two languages I use).

**Comment by gillesdubois** [comment]
Hi @LMS235 

Sorry for the delay.

The issue with your PR is that we don't understand why you re-ajusted all the lines.
Validating this PR would mean that we have to do the same of all the translations ... Which can be a bit time consuming for not a lot of advantages.

I'll wait for your answer, we won't close this PR until we found a compromise :) 

Regards,
Gilles.

**Comment by LMS235** [comment]
The background is the translation work. It is much easier to translate the texts cleanly and check what is open etc. if the line numbers correspond to the entry numbers. Of course, it would be best for all languages that the entry number is equal to the line number.

It is a bit of work once, but it should pay off in the future.

**Comment by gillesdubois** [comment]
Hi @LMS235 

Again sorry for the delay but the problem is we cannot force contributors to manage the translation that way and it'll most likely induce human error in the process.

We are currently reworking a big part of the product and make the translation work on a newer / more modern system.
I think this new system will most likely bring a better organization for the translations.

Thank you for taking the time to review and propose a better alternative for the translation.

Regards,
Gilles.

**Pull request closed without merging**
