### PR TITLE
Fix #545

### LINKED ISSUE #545: Sort by ipaddress not working in ocsreports 2.5
### General informations
Operating system : CentOS 7.4.1807

### Server installation method ( Only one choice )
- [X ] Install SH (tgz)

### Server informations
Php version : 5.4.16
Apache version : 2.4.6

### OCS Inventory informations
Ocsreports version : 2.5

### Problem's description
I click on the ip address column from All computers page but the ip addresses of the first computers are not ordered: http://prntscr.com/kik9oc

I mean, not all ip addresses are not ordered, just some of them, let's say, the first one hundred of more thann.ipaddress out one thousand ip addresses.

### PR DESCRIPTION
**Pull request by charleneauger**
## Status
**READY**

## Description
Fix bug Ipaddress sorting in all computer

## Related Issues
#545 

## Todos
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by pchamo** [comment]
I wonder if there are doble quotes missing:

> 		$sort= " order by INET_ATON("n.ipaddress") ".$sens;

not:

> 		$sort= " order by INET_ATON(n.ipaddress) ".$sens;

In any case, I think the ocs developers team should defined where the network info is recorded, because I'm noticing ocsreports is showing information both from the hardware table and also from the networks table. I wonder why two tables are needed.

**Comment by charleneauger** [comment]
Hi @pchamo ,

Your remark is really interesting. In fact, the hardware table records all the main information of the computer and the main IP address is one of them. It would become complicated to remove it from this table.

Regards,
Charlene

**Comment by pchamo** [comment]
Ok, but something is wrong for some few of our computers, for instance, look at this:

http://prntscr.com/kmjmyv

For that portable computer:

- Network info: only a bluetooth device info is shown, no IP address
- All computers page shows MAC addresss, no ip address and no gateway address
- Computer details page: it does show the ip address.

So, for that computer, there is a bug:

http://prntscr.com/kmjr6k

Thank you

**Comment by alacn1** [comment]
I think "0dfbd8fc Fix #545" broke IpDiscover Non identified peripherals list.
It shows empty table.

**Pull request merged**
