### PR TITLE
Lots of fixes

### PR DESCRIPTION
**Pull request by saep-es**
* Changes related with version 2.3:
	* Some duplicate codes have been removed;
	* Many missing codes in the brazilian portuguese version have been included/translated;
	* Many codes in the brazilian portuguese version still in english/french have been translated;
	* Many translations were retranslated considering contextualization;
	* Several translations were re-adapted;
	* Many problems of accentuation, uppercase and punctuation have been solved;
	* Many unused codes in the source code have been removed (brazilian portuguese, english and french);
	* Error and warning messages were normalized.
* On "828 Remove computers with inventory older than"
	* Q: Older than what?
* On "254 Path of the key (Ex: SOFTWARE\Mozilla)"
	* Q: Why the "\" is suppressed?
* On Management > Local import > Manual entry
	* Q: What is the meaning of "_M"?
	* Q: "28 Computer count" is really ok?
* The code 400 is used in function_snmp.php, but it is not on the language files
	* S: add the code and a pro

### CODE REVIEW

**Comment by gillesdubois** [comment]
Hi,

In the first place, thanks for your contribution.

```
On "828 Remove computers with inventory older than"
Q: Older than what?`
```

A : This translation is used for : Remove computers with inventory older than X days
X is custom depending on the user choice and displayed programmatically

```
On "254 Path of the key (Ex: SOFTWARE\Mozilla)"
Q: Why the "" is suppressed?
```

A : I don't know, was there quotes in the past ?

```
On Management > Local import > Manual entry
Q: What is the meaning of "_M"?
```

A : _M Stand for manual, it's a way to divide automated and manual entry from the reports

```
Q: "28 Computer count" is really ok?

```

A : Yes, "Computer count" is an accurate translation

```
The code 400 is used in function_snmp.php, but it is not on the language files
S: add the code and a pro
```

A : Yes, you're right.
It look like it's an error when the function parameter is not a numeric and not equal to ""
I think the return itself should be something like "return false" and not a translation.

Regards,
Gilles Dubois.

**Comment by saep-es** [comment]
Hi, 

I am not so familiar with GitHub, but all that I wanted was contribute with the OCS project.

26 days ago I submitted new versions of 3 language files: brazilian portuguese, english and french.

I am not sure if these submissions were ok (with a correct work flow).

Did you have chance to see these 3 files? I am supposed to do something else?

Regards,

Ricardo Vargas

**Comment by gillesdubois** [comment]
Hi, @saep-es 

I answered you, i was waiting for your reply since i need to see if you agree with what i said.
Maybe we need to discuss about some of your questions :) 
Every question were fine and justified but could we try to find solution together ?

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
ping @saep-es ?

**Pull request closed without merging**
