### PR TITLE
Bug sso ldap

### PR DESCRIPTION
**Pull request by sborion**
### Status
**READY

### Description
In LDAP with SSO, use ldap.php auth and not always_ok.php.
but dont check password, only check if user existe and get parameters.

For issue #1339

### CODE REVIEW

**Comment by Lea9250** [comment]
Hi @sborion,

Thanks for taking the time to contribute. 
Applying the changes from this PR, it seems like there might be something missing : using correct credentials I am not able to get past the login prompt, it keeps showing at each connection attempt.
Did every change you made get committed ?

Regards,
Léa

**Comment by Lea9250** [comment]
Hi @sborion,

Any update on this subject ?

Best regards,
Léa

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this PR now.

Regards,
Charlene

**Comment by matt6697** [comment]
Issue was related with `return isset($info[0]["dn"]);`returning `1`or `0` in the new code of `verif_pw_ldap($login, $mdp)` function. This `function verif_pw_ldap($login, $pw)` should return either `"OK"` or `"BAD LOGIN OR PASSWORD"` string to make the following `if`statements work correctly :

```
$login_successful = verif_pw_ldap($login, $mdp);
if($login_successful == "BAD LOGIN OR PASSWORD") {
    $login_successful = $l->g(180);
}
// Check if defaultRole is not empty
if($login_successful == "OK") {
    [...]
}
```

Both LDAP & SSO login work with `return (isset($info[0]["dn"]) ? "OK" : "BAD LOGIN OR PASSWORD");`

Fix proposed in PR https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1579

**Comment by matt6697** [comment]
Hi @sborion and @Lea9250 , would you mind to take some time to try the fix proposed in PR #1579 and check if it corrects the issue encountered with this closed PR ?

**Pull request closed without merging**
