### PR TITLE
Add LDAP check user membership in static group and setup user role

### PR DESCRIPTION
**Pull request by Negatifff**
### Status
**READY/IN DEVELOPMENT/HOLD** (remove the irrevelant words)

### Description
A few sentences describing the overall goals of the pull request's commits.

### Documentation
In the case, your pull request need the documentation to be modified, please say it here.
You can also directly create a pull request for the documentation here : https://github.com/OCSInventory-NG/Wiki

Note : Merge process will be faster if the documentation is already written

### CODE REVIEW

**Comment by sebastianuw** [comment]
Thanks for this code! This is a great help for my setup where memberOf isn't available.

I did find an issue with it, however. AD stores the full DN of the user in the member group attribute. I needed to modify the ldapsearch in "backend/AUTH/methode/ldap.php"  to include the full DN of the user.

Could an optional field be added to set the OU where users are located? And if set have it prepend a "CN=" to $login?

**Comment by charleneauger** [comment]
Hi @Negatifff ,

In the next 2.9.2 release, we updated the LDAP user search fields in the configuration, see the PR https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/1298 and the [PR for the updated LDAP documentation](https://github.com/OCSInventory-NG/Wiki/pull/134).
Your contribution was in line with the old configuration which means that I cannot validate it.
Thank you for your contribution yet.

Regards,
Charlene Auger

**Comment by Negatifff** [comment]
> Hi @Negatifff ,
> 
> In the next 2.9.2 release, we updated the LDAP user search fields in the configuration, see the PR #1298 and the [PR for the updated LDAP documentation](https://github.com/OCSInventory-NG/Wiki/pull/134). Your contribution was in line with the old configuration which means that I cannot validate it. Thank you for your contribution yet.
> 
> Regards, Charlene Auger

it is a pity that you stubbornly do not want to support ldap schemes, where the binding of a user in a group is stored in the group, and not in the user.

**Comment by Negatifff** [comment]
> Hi @Negatifff ,
> 
> In the next 2.9.2 release, we updated the LDAP user search fields in the configuration, see the PR #1298 and the [PR for the updated LDAP documentation](https://github.com/OCSInventory-NG/Wiki/pull/134). Your contribution was in line with the old configuration which means that I cannot validate it. Thank you for your contribution yet.
> 
> Regards, Charlene Auger

it is a pity that you stubbornly do not want to support ldap schemes, where the binding of a user in a group is stored in the group, and not in the user.

**Pull request closed without merging**
