### PR TITLE
Converted a few files from ISO-8859-1 to UTF-8, restore damaged characters

### PR DESCRIPTION
**Pull request by nirgal**
This is only about comments and license files (French), there is no impact on the code.

I'm afraid this is based on fixed permissions branch.
If you don't want that, ping me and I'll make a branch based on master.

### CODE REVIEW

**Comment by nirgal** [comment]
I just added a commit in that branch that restore the damaged text in French comments :)

**Comment by gillesdubois** [comment]
Hello, 

First, thanks you for contributing to OCSInventory-NG !
I think it will be better if you just propose the encoding change on that pull request ...
Your pull request on commit "Fix Permissions" is already opened so, please remove that commit from this pull request and i will accept it.

Regards, Gilles Dubois.

**Comment by nirgal** [comment]
> Your pull request on commit "Fix Permissions" is already
> opened so, please remove that commit from this pull request
> and i will accept it.

Ok.
I'll rearrange the order of the commits now. Please stand by.

**Comment by nirgal** [comment]
Here you are, it doesn't depends on permissions change any more.
(git rocks)

**Pull request merged**
