### PR TITLE
Clean up code with PhpStorm

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by MyTheValentinus** [comment]
Hello @stweil,
Thank for your contribution,
Pull request will be merged soon after test.
Have nice day!

**Comment by MyTheValentinus** [comment]
Hello @stweil,
Thank for your pull request, for merge accept please remove /librairies folder from your commit.
Thanks

**Comment by stweil** [comment]
Done. I rebased the PR and removed /libraries from the commit.

**Comment by MyTheValentinus** [comment]
Thanks @stweil i merge your request !

Have nice day

**Pull request merged**
