### PR TITLE
Project update

### PR DESCRIPTION
**Pull request by AnaelMobilia**
PHP 5.4 (requierement & code style)
PHP codestyle (part of PR #142 )
Fix few HTML errors
#152 : check requierements on update
Fixs for W3C validator

### CODE REVIEW

**Comment by gillesdubois** [comment]
Hi,

For the next time, could you please submit your PR when all your commits are pushed ?
Each time you add a push "On the fly" we need to repeat some tests.

It would be nice to slip your PR into specific theme so we don't have to test the whole project each time.
Because one PR with name "project update" is a little ... fuzzy.

For example : 
- Updating dashboard page
- Updating Teledeploy page
- Move library

Even if you push 50 PR, it's easier for us to tests multiples "modules" than the whole update.

Problems encountered with your PR : 

- Stats page broken ( OTHER tabs' graphic doesn't work anymore )

- Teledeploy stats broken ( Same problem than the one above )

- Is that "<? ?>" instead of "<?php ?>" really needed ? 
These 2 notations do the same thing ...

- Datatables update generate a glitch on display ( see attached screen )
capture du 2016-11-07 14-38-58

Going back to testing ;-)

Thanks for your contribution,
Gilles Dubois.

**Comment by AnaelMobilia** [comment]
Hello Gilles,

I take note for the separated PR, next will be made as requested ! :)
I try to manage really separated commits, but I understand the difficulty when you have all theses one !

For the stats, it's indeed #144 : actual graph tools doesn't support html5 (orphaned projet). The choice of bootstrap implied html5... snake probleme here !
As mitigation, I can purpose to work on the migration of the graph tools after the PR is merged.
I think to highcharts for doing this. Your opinion ?


The "<?=" equals to "<?php echo". Indeed they do the same thing :-)
IMHO, the first one is more readable as it can be integrated easierly in html code (and so have the power of an ide).On using this syntax I found html errors on the header_html().
It's like about religious here. If there is a problem with it, I can made a commit to revert it :-)


I take note for the glitch, I will try to reproduce it.
Just to be sure, have you cleared the browser cache (images was updated with the plugin) ?

Thanks for your help !
Regards

**Comment by MyTheValentinus** [comment]
Hello,
Shortcut <?= is not activate by default in php.ini configuration on new php versions.

**Comment by AnaelMobilia** [comment]
@MyTheValentinus please read http://php.net/manual/fr/language.basic-syntax.phptags.php and http://php.net/manual/fr/ini.core.php#ini.short-open-tag
The <?= syntax was depending on short_open_tag for version previous to 5.4.0.
For every version greater or equal to PHP 5.4.0, the syntax is *always* available (mandatory by the PHP team)

**Comment by gillesdubois** [comment]
Thanks for your understanding.

Cache was cleared.

I am sorry but i can't accept this PR with the actual problems.

Even if github is designed for devs we need to have all of our features working in the master branch.

If you want to be merged, i think the best thing to do is to create a separate PR for :
- datatables library
- code refractor
- html 5 ( in stand by waiting for elychart update )
- code spell refractor

Gilles Dubois.

**Comment by MyTheValentinus** [comment]
```
; This directive determines whether or not PHP will recognize code between
; <? and ?> tags as PHP source which should be processed as such. It is
; generally recommended that <?php and ?> should be used and that this feature
; should be disabled, as enabling it may result in issues when generating XML
; documents, however this remains supported for backward compatibility reasons.
; Note that this directive does not control the <?= shorthand tag, which can be
; used regardless of this directive.
; Default Value: On
; Development Value: Off
; Production Value: Off
; http://php.net/short-open-tag
short_open_tag = Off
```

Okay, do not affect <?= but all <?

**Comment by AnaelMobilia** [comment]
@gillesdubois I have notice :-)

@MyTheValentinus There isn't any "<? " on these PR, due to your pasted text : server dependent... :)

**Pull request closed without merging**
