### PR TITLE
Fix permissions

### PR DESCRIPTION
**Pull request by nirgal**
There is only one real executable script: ipdiscover-util.pl
All the images, php files, css, javascript and so on are not executable from the command line.

### CODE REVIEW

**Comment by gillesdubois** [comment]
Hello,

That pull request is ok for me but i need some time to verify if all theses change mode don't break something...
I will take a look on this and give you a feedback today or tomorow.

Regards, Gilles Dubois

**Comment by nirgal** [comment]
I refreshed the patch against master, since pull request 2 went in first.
If there are more conflicts and I'm not around, that commit can be reproduced using:
```
for file in *; do find $file -type f -executable -exec chmod -x {} \;; done
chmod +x ipdiscover-util.pl
```
( You don't want to touch your .git directory, hence the * )

**Comment by kapouik** [comment]
Need to verify before if it don't break php in cgi or fpm.

**Comment by nirgal** [comment]
I just tested with php5-cgi and it does work ok without the +x.
(I did not test php5-fpm)

The config snippet is:
Action application/x-httpd-php /cgi-bin/php5
ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/

So that when one connect to:
http://localhost/ocsreports/
he is actually hitting URL
/cgi-bin/php5/ocsreports/index.php
that runs /usr/lib/cgi-bin/php

That file need the +x mode.

I did not test other http daemons, but basically, if the file doesn't start with `#!`, like `#!/usr/bin/php`, it is highly unlikely that mode +x is required, since it would not run from the command line anyway.



There is no urgency on that issue.

**Comment by nirgal** [comment]
Refreshed against master

**Comment by gillesdubois** [comment]
Hello,

Firstly, sorry to keep you waiting.
Ocs reports 2.2 add a lot of new functionality and enhancement so i can't merge this full request because some permissions have been changed.
I close this pull request but i will apply theses changes later with last permissions modification (I will add these changes while RC i think).

Thx you for contributing to ocs inventory ng !
Regards, Gilles Dubois.

**Comment by nirgal** [comment]
I just refreshed my branch https://github.com/nirgal/OCSInventory-ocsreports/tree/permissions

You recently added another .pl file with shebang, so that the script above is no longer relevent.

Here's a new version:
```
for file in *; do find $file -type f -executable -exec chmod -x {} \;; done
chmod +x ipdiscover-util.pl
chmod +x plugins/main_sections/ms_plugins/client.pl
```

You can run it anytime to fix the permissions.

**Comment by nirgal** [comment]
Any news on this issue?
The images, text, php files and so on, are still flagged as executable !

Please keep it open, or you will forget it!

**Pull request closed without merging**
