### PR TITLE
Consistency improvment in french language

### PR DESCRIPTION
**Pull request by steph78630**
- Improved consistency of informations displayed in french language (tag> Label, etc.)
- Add "Period" word for the choice of the period in Statistics> Number of connections per day
- Replace "Actions" word by "Delete" in english and "Suppression" in french (better adapted to context)

### CODE REVIEW

**Comment by gillesdubois** [comment]
Hi,

Sound good but one thing, you got an additional translation that may come from a plugin ( 14000 Gestion des clés Office ). Since Office is not installed by default can you remove this translation ?

Regards,
Gilles Dubois.

**Comment by steph78630** [comment]
Hi Gilles,

no problem, i do it.

Regards, Stéphane

**Comment by steph78630** [comment]
It's done !

**Comment by steph78630** [comment]
New word add in statistics > Number of connections per day

**Comment by gillesdubois** [comment]
Hi,

I can't merge your pull request.
You need to split your changes in differents branches and Pull Requests.

There will be new guidelines to help you.

Regards,
Gilles Dubois.

**Pull request closed without merging**
